# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prothought < Formula
  desc "Thought tracker with hashtag support"
  homepage "https://github.com/povilaspetkevicius/prothought"
  version "0.1.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/povilaspetkevicius/prothought/releases/download/v0.1.1/prothought_Darwin_x86_64.tar.gz"
    sha256 "d556bb7f35ff8d86057b3d95372a45f77ac65e83fa173cf8e0fab5aad332bc28"

    def install
      bin.install "prothought"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/povilaspetkevicius/prothought/releases/download/v0.1.1/prothought_Darwin_arm64.tar.gz"
    sha256 "bf8f5c410f1de9ce436e62549c3dff9d25b3b42249e1259772a8728da3feb7ea"

    def install
      bin.install "prothought"
    end
  end

  test do
    system "#{bin}/prothought", "--version"
  end
end
