# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prothought < Formula
  desc "Thought tracker with hashtag support"
  homepage "https://github.com/povilaspetkevicius/prothought"
  version "0.1.2"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/povilaspetkevicius/prothought/releases/download/v0.1.2/prothought_Darwin_x86_64.tar.gz"
    sha256 "b04a7d76e1202a3bcd621f4636a0f34349612d3f70598726cd159fa9c95099c2"

    def install
      bin.install "prothought"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/povilaspetkevicius/prothought/releases/download/v0.1.2/prothought_Darwin_arm64.tar.gz"
    sha256 "333fdf33a9177a5e265640c4b931cb7765866f26f37a32fbf504faae617e2223"

    def install
      bin.install "prothought"
    end
  end

  test do
    system "#{bin}/prothought", "--version"
  end
end
